version: '3.8'

services:
  # Development Backend with live reload
  backend:
    build: 
      context: ./backend  # ← Point to backend folder
      dockerfile: Dockerfile
    container_name: conversational-store-dev
    ports:
      - "5000:5000"
    env_file:
      - .env  # ← Point to backend/.env
    volumes:
      - ./backend:/app  # ← Mount backend folder
      - ./data:/app/data  # ← Mount data folder
    command: ["python", "app.py"]

  # move to Separate file for easy debugging
  # frontend:
  #   build: 
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   container_name: ai-commerce-frontend
  #   ports:
  #     - "80:80"
  #   env_file:
  #     - .env
  #   restart: unless-stopped
  #   networks:
  #     - app-network

networks:
  app-network:
    driver: bridge