version: '3.8'

services:
  # Backend Service
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: conversational-store-backend
    ports:
      - "5000:5000"
    depends_on:
      chromadb:
        condition: service_healthy
    environment:
      - CHROMA_HOST=chromadb
      - CHROMA_PORT=8000
      - FLASK_ENV=development
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    networks:
      - backend-network

  # ChromaDB Service
  chromadb:
    image: chromadb/chroma:latest
    container_name: chroma-server
    ports:
      - "8000:8000"
    volumes:
      - ./data/chroma_db:/chroma/chroma
    environment:
      - CHROMA_HOST=0.0.0.0
      - CHROMA_PORT=8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/heartbeat"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge
