version: '3.8'

services:
  # Frontend Service
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ai-commerce-frontend
    ports:
      - "80:80"
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - app-network

  # Backend Service
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: conversational-store-backend
    ports:
      - "5000:5000"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - app-network

  # ChromaDB Service
  # chromadb:
  #   image: chromadb/chroma:latest
  #   container_name: chroma-server
  #     .env
  #   healthcheck:
  #     test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8000/api/v2/heartbeat"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 3
  #   restart: unless-stopped
  #   networks:
  #     - app-network

networks:
  app-network:
    driver: bridge
